//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




That seaport will be soon ours.

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from field, assault and capture
the <marker name = 'target1'>sea port</marker> objective.



<br/><br/>PMC Hostile Sea<br/><br/>

GEN SITREP<br/>
Russians have been receiving lot of supplies and armor from the ocean supply lanes. We are
now trying to put end to this by taking out their supply lines.
<br/><br/>

INTEL<br/>
In the desert there is some armored vehicles, we do not know if they are capable of launching
reinforcements there. The target itself contains some infantry but no armored vehicles.
<br/><br/>

ORDERS<br/>
Alpha team <marker name = 'start'>start</marker> from field, assault and capture
the <marker name = 'target1'>sea port</marker> objective neutralizing all enemy forces in the area.
<br/><br/>

TACTICAL<br/>
Try to make this as fast as possible, you could take the objective before any reinforcements
can be sent to back up the Russians. Watch out those Russian patrols.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture sea port"];
objective1 setSimpleTaskDescription ["Capture sea port", "Capture sea port", "Capture sea port"];
