//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




We must hold this castle!

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


NATO guys are defending the <marker name = 'defend'>Castle</marker> against Russian 
attack.



<br/><br/>PMC Defend Castle<br/><br/>

GEN SITREP<br/>
We must hold this key piece of real estate, do not let it fall into enemy hands.
<br/><br/>

INTEL<br/>
The Russians are attacking from all directions, only infantry is expected.
<br/>

ORDERS<br/>
You two guys are only thing we have left down there, hold 
the <marker name = 'defend'>Castle</marker> against Russian attack at any cost. Your mission
is accomplished when the enemy gives up.
<br/><br/>

TACTICAL<br/>
There are ammo boxes in the ground level, but be careful when you are down there 
as enemies can easily pick you off!
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Hold the Castle."];
objective1 setSimpleTaskDescription ["Hold the Castle.", "Hold the Castle.", "Hold the Castle."];
