//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




I lost the battle, I'm prisoner of war... this SUCKS...






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Russian POW camp... I guess
its just keeping alive and following the commies orders.



<br/><br/>PMC Escape<br/><br/>

GEN SITREP<br/>
I'm been POW for 12 days now with three other US soldiers... I dont know much whats happening in the War.
<br/><br/>

INTEL<br/>
No idea.
<br/><br/>

ORDERS<br/>
No orders.
<br/><br/>

TACTICAL<br/>
Basic survival. Avoid eye contact to the Russians, no sudden movements... keeping
within the area with no movement or they surely would shoot me.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Take command of the survivors and get them into Nogova <marker name = 'airbase'>Airbase</marker> area."];
objective2 setSimpleTaskDescription ["Take command of the survivors and get them into Nogova <marker name = 'airbase'>Airbase</marker> area.", "Take command of the survivors and get them into Nogova <marker name = 'airbase'>Airbase</marker> area.", "Take command of the survivors and get them into Nogova <marker name = 'airbase'>Airbase</marker> area."];
objective1 = player createSimpleTask ["Stay alive?"];
objective1 setSimpleTaskDescription ["Stay alive?", "Stay alive?", "Stay alive?"];
