//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Ambushing Russians is fun activity!

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


NATO small team starts from the city of Arudy, which is 
the <marker name = 'target'>target</marker> for todays ambush.
Russian <marker name = 'convoy'>convoy</marker> is travelling through it. NATO's 
objective is to eliminate that convoy.



<br/><br/>PMC Ambush 2<br/><br/>

GEN SITREP<br/>
We are disrupting Russian convoys on this island.
<br/><br/>

INTEL<br/>
Convoy containing infantry and few armored vehicles is moving through the Arudy.
<br/><br/>

ORDERS<br/>
NATO team must eliminate all units in the <marker name = 'convoy'>convoy</marker> which
is travelling through this area.
<br/><br/>

TACTICAL<br/>
Try to place satchel charges in the road between buildings in 
the <marker name = 'target'>arudy</marker> so most of the heavy armor will be blown to bits
before the fighting even starts.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Stop and Destroy the Convoy"];
objective1 setSimpleTaskDescription ["Stop and Destroy the Convoy", "Stop and Destroy the Convoy", "Stop and Destroy the Convoy"];
