//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Designers Notes", "This was one of the early OFP missions created by Snake Man.<br/><br/>Must have been something like 2001 or 2002 era when we played a lot of LAN multiplayer at PMC WHQ."]];
player createDiaryRecord ["Diary", ["Diary", "I must keep very very low behind the trees to avoid detection by he russians. If they see me before we open fire, the surprise element is gone.<br/><br/>I must take cover when reloading and change firing positions after each reload."]];
player createDiaryRecord ["Diary", ["Mission", "Ambush teams <marker name = 'start'>start</marker> both sides of the road. Set up nice ambush in the <marker name = 'road'>road</marker> and don't let anyone escape.<br/><br/><br/><br/>PMC Ambush<br/><br/>NATO has gathered some intelligence and belives a two squad Russian infantry patrol is heading towards Lolisse by the road. We must ambush and kill them.<br/><br/>Approx two squads of infantry only is travelling the road towards north. They are coming from <marker name = 'ruskies'>here</marker><br/><br/>Ambush team <marker name = 'start'>start</marker> in the road, set up ambush in the road about <marker name = 'road'>here</marker><br/>Watch out soldier, dont let anyone escape alive!<br/><br/>Keep low, take cover when reloading. Don't let the Russians catch a breath.<br/><br/>"]];

// tasks need to be in reversed order
objective1 = player createSimpleTask ["Kill all Russians"];
objective1 setSimpleTaskDescription ["Kill all Russians", "Kill all Russians", "Kill all Russians"];
