//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




We got the get the heck out of this airbase or we will be POW or KIA.

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'evac'>start</marker> from base. Hold off the enemy until
Black Hawk helo picks you up.
<br/><br/>
Goodspeed son.



<br/><br/>PMC Evac!<br/><br/>

GEN SITREP<br/>
We are evacuating Malden island. All NATO forces have orders to leave the island
as quickly as possible. Russians are overrunning the island and we have no forces to
stop them at the moment. We'll fight an another day.
<br/><br/>

INTEL<br/>
Russians are coming from both SW and NW. Infantry and tanks, no air activity. Russians 
have overrun our bases down the south and recon patrol reported (until we lost contact) 
that they are already in Saint Louis.
<br/><br/>

ORDERS<br/>
Mine the airfield <marker name = 'evac'>area</marker> for incoming enemy tanks. Your mission is 
to stay alive and get the hell out of Malden <marker name = 'evac'>Airfield</marker>, which will 
be overrun by enemy forces in any minute now. First two Black Hawk evac flights will take 
out two squads to safety while you mine the airfield so enemy has its hands full. When the 
Black Hawks return they will extract your team out of there.
<br/><br/>

TACTICAL<br/>
Stay alive until then, dont try to be a freaking hero soldier, you are overrun as we speak, 
nothing you can do about it...
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Hold off the enemy until extract."];
objective1 setSimpleTaskDescription ["Hold off the enemy until extract.", "Hold off the enemy until extract.", "Hold off the enemy until extract."];
