//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Designers Notes", "This was one of the early OFP missions created by Snake Man.<br/><br/>Must have been something like 2001 or 2002 era when we played a lot of LAN multiplayer at PMC WHQ."]];
player createDiaryRecord ["Diary", ["Diary", "Time for some hunting!"]];
player createDiaryRecord ["Diary", ["Mission", "You'll start on NATO HQ Airbase <marker name = 'start'>here</marker>.<br/><br/>Hunt down the Russian Colonel and neutralize him.<br/><br/>Colonel Hunt<br/><br/>Everon is under Russian control, NATO will try to interfere.<br/><br/>Lot of Russians scattered all around the island. No AAA defenses known at this time. Some armored vehicles has been detected by satellite. The Russian Colonel is traveling around the island on UAZ with hes Spez Natz bodyguards. He is inspecting the positions of his troops for this day and through the night.<br/><br/>You are to hunt down the Russian Colonel and neutralize him. You are free to engange other enemies as well, but the Colonel is your primary objective.<br/><br/>Be very careful when operating behind enemy lines, if you must engage the enemy forces its certain that it will draw attention and armored vehicles will investigage. So if you must strike, do it fast and escape to safe areas.<br/>You will be using Black Hawk helo for insertion and extraction. There are radio calls for insertion and extraction. Use them wisely. There is also some ammo boxes in our base near the buildings."]];

// tasks need to be in reversed order
objective2 = player createSimpleTask ["Return to base"];
objective2 setSimpleTaskDescription ["Return to base", "Return to base", "Return to base"];
objective1 = player createSimpleTask ["Eliminate Russian Colonel"];
objective1 setSimpleTaskDescription ["Eliminate Russian Colonel", "Eliminate Russian Colonel", "Eliminate Russian Colonel"];
