//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Designers Notes", "This was one of the early OFP missions created by Snake Man.<br/><br/>Must have been something like 2001 or 2002 era when we played a lot of LAN multiplayer at PMC WHQ.<br/><br/>JAM means joint weapons and magazines, and OFP addon initiative which also introduced high dispersion (HD) weapons/magazines."]];
player createDiaryRecord ["Diary", ["Diary", "Empty main section."]];
player createDiaryRecord ["Diary", ["Mission", "Empty plan section."]];

// tasks need to be in reversed order
