//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "Empty main section.
"]];
player createDiaryRecord ["Diary", ["Mission", "Empty plan section.
"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Search and Destroy"];
objective1 setSimpleTaskDescription ["Search and Destroy", "Search and Destroy", "Search and Destroy"];
