//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "Empty main section.
"]];
player createDiaryRecord ["Diary", ["Mission", "Empty plan section.
"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Sniper team eliminates Colonel"];
objective2 setSimpleTaskDescription ["Sniper team eliminates Colonel", "Sniper team eliminates Colonel", "Sniper team eliminates Colonel"];
objective1 = player createSimpleTask ["US neutralizes sniper team"];
objective1 setSimpleTaskDescription ["US neutralizes sniper team", "US neutralizes sniper team", "US neutralizes sniper team"];
