
setDate [2006, 11, 17, 0, 0];
PMCHQ = [ West, "BASE" ];
[] execVM "PMC\PMC_Set_Mission_Time.sqf";
[] execVM "PMC\PMC_Tasks.sqf";
[] execVM "PMC\PMC_weather_with_mp_parameter.sqf";

call compile preProcessFileLineNumbers "PMC\PMC_SetAISkill.sqf";
private _skill = ["PMC_EnemySkillLevel", 0] call BIS_fnc_getParamValue;
private _PMC_EnemySkillLevel = [_skill] call compile preProcessFileLineNumbers "PMC\PMC_Get_Skill_Level.sqf";

[group badguy1, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy2, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy3, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy4, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy5, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy6, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy7, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy8, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy9, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy10, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy11, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy12, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy13, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy14, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy15, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy16, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy17, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy18, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy19, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy20, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy21, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy22, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy23, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy24, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy25, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy26, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy27, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy28, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy29, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy30, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy31, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy32, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy33, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy34, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy35, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy36, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy37, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy38, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy39, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy40, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy41, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy42, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy43, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy44, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy45, _PMC_EnemySkillLevel] call PMC_SetAISkill;
[group badguy46, _PMC_EnemySkillLevel] call PMC_SetAISkill;

[] execVM "PMC\PMC_Objectives.sqf";
