//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Designers Notes", "This was one of the early OFP missions created by Snake Man.<br/><br/>Must have been something like 2001 or 2002 era when we played a lot of LAN multiplayer at PMC WHQ."]];
player createDiaryRecord ["Diary", ["Diary", "Our task today is to clear our Petrovice, should be fun."]];
player createDiaryRecord ["Diary", ["Mission", "Alpha team <marker name = 'start'>start</marker> from hill. Clear the <marker name = 'target1'>city</marker> area from Russians.<br/><br/>PMC Sniper Alley<br/><br/>GEN SITREP<br/>Russians are occupying Petrovice and snipers terrorise the citizens.<br/><br/>INTEL<br/>Some infantry and snipers are defending the city. The snipers are positioned in the way that they cover the most engagement areas in the city, be very careful with them. We have also some movement in far SE, might be some reinforcements gathering up.<br/><br/>ORDERS<br/>Alpha <marker name = 'start'>start</marker> from the hill. Proceed and clear out <marker name = 'target1'>Petrovice</marker> from any Russians. Watch out for the sniper activity in the city, they are indicated to be very deadly.<br/><br/>TACTICAL<br/>Be very careful with the snipers!"]];

// tasks need to be in reversed order
objective1 = player createSimpleTask ["Clear Petrovice"];
objective1 setSimpleTaskDescription ["Clear Petrovice", "Clear Petrovice", "Clear Petrovice"];
