//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "Empty main section.
"]];
player createDiaryRecord ["Diary", ["Mission", "Empty plan section.
"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Shoot down enemy helos"];
objective1 setSimpleTaskDescription ["Shoot down enemy helos", "Shoot down enemy helos", "Shoot down enemy helos"];
