//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Designers Notes", "This was one of the early OFP missions created by Snake Man.<br/><br/>Must have been something like 2001 or 2002 era when we played a lot of LAN multiplayer at PMC WHQ."]];
player createDiaryRecord ["Diary", ["Mission", "Shoot down enemy helos."]];

// tasks need to be in reversed order
objective1 = player createSimpleTask ["Shoot down enemy helos"];
objective1 setSimpleTaskDescription ["Shoot down enemy helos", "Shoot down enemy helos", "Shoot down enemy helos"];
