//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Today we clear out this forsaken town.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "
1-1-A team <marker name = 'start'>start</marker> from the air. Clear <marker name = 'target1'>town</marker> objective.




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Clear town"];
objective1 setSimpleTaskDescription ["Clear town", "Clear town", "Clear town"];
