//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Intel has not been able to locate the scuds, those bastards!
<br/><br/>





"]];
player createDiaryRecord ["Diary", ["Mission", "Empty plan section.
"]];
// tasks need to be in reversed order
