//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Designers Notes", "This was one of the early OFP missions created by Snake Man.<br/><br/>Must have been something like 2001 or 2002 era when we played a lot of LAN multiplayer at PMC WHQ."]];
player createDiaryRecord ["Diary", ["Diary", "Special Forces baby!"]];
player createDiaryRecord ["Diary", ["Mission", "NATO Special Forces <marker name = 'Attack'>start</marker> from South East from the Russian held <marker name = 'Defence'>target</marker> city.<br/><br/>NATO objective is to neutralize all Russians and destroy all their equipment.<br/><br/>PMC Night City Raid<br/><br/>Command has decided to eradictate Russian occupancy from Chapoi.<br/><br/>Our intel estimates there is approximately one platoon strength of defences and some support vehicles.<br/><br/>NATO Speacial Forces team <marker name = 'Attack'>start</marker> from just South East from Chapoi, they approach the <marker name = 'Defence'>target</marker> area under the cover of darkness. Mission is accomplished when all Russian infantry plus equipment is destroyed.<br/><br/>It would be stupid to think Russians don't have patrols in the area, so watch out for them. Place Satchel Charges under the vehicles you want to destroy. Don't worry about nuking half the city, you're authorized to use any force necessary to get the job done."]];

// tasks need to be in reversed order
objective1 = player createSimpleTask ["Neutralize Russians"];
objective1 setSimpleTaskDescription ["Neutralize Russians", "Neutralize Russians", "Neutralize Russians"];
