//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Designers Notes", "This was one of the early OFP missions created by Snake Man.<br/><br/>Must have been something like 2001 or 2002 era when we played a lot of LAN multiplayer at PMC WHQ."]];
player createDiaryRecord ["Diary", ["Mission", "You must hold Montignac town at all costs."]];

// tasks need to be in reversed order
objective2 = player createSimpleTask ["Russians Hold Montignac"];
objective2 setSimpleTaskDescription ["Russians Hold Montignac", "Russians Hold Montignac", "Russians Hold Montignac"];
objective1 = player createSimpleTask ["US Hold Montignac"];
objective1 setSimpleTaskDescription ["US Hold Montignac", "US Hold Montignac", "US Hold Montignac"];
