//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "Empty main section.
"]];
player createDiaryRecord ["Diary", ["Mission", "Empty plan section.
"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Russians Hold Montignac"];
objective2 setSimpleTaskDescription ["Russians Hold Montignac", "Russians Hold Montignac", "Russians Hold Montignac"];
objective1 = player createSimpleTask ["US Hold Montignac"];
objective1 setSimpleTaskDescription ["US Hold Montignac", "US Hold Montignac", "US Hold Montignac"];
