//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "Empty main section.
"]];
player createDiaryRecord ["Diary", ["Mission", "Empty plan section.
"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Russians defend road block"];
objective2 setSimpleTaskDescription ["Russians defend road block", "Russians defend road block", "Russians defend road block"];
objective1 = player createSimpleTask ["NATO capture road block"];
objective1 setSimpleTaskDescription ["NATO capture road block", "NATO capture road block", "NATO capture road block"];
