//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Gosh, another day and another damned flyboy mission. Time to whoop some Russian tanks around.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from the air.
assault <marker name = 'target1'>airbase</marker> and neutralize all vehicles.



<br/><br/>Gunship Assault 1<br/><br/>

1. SITUATION:<br/>
Our war against the Russians start now. It is up to us to prevent the red bear to take over the free world, which they can easily do if they capture and hold these oil resources.
<br/><br/>

2. MISSION:<br/>
Alpha team <marker name = 'start'>start</marker> from the air. Proceed to assault <marker name = 'target1'>airbase</marker> until all vehicles have been neutralized.
After your have achieved your objectives, use radio (0-0-1) to call end mission. Good luck.
<br/><br/>

3. EXECUTION:<br/>
Be sure to watch your backs out there, keep your men alive and healthy. See you 
later on the HQ, goodspeed you all.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
You have flight of A10's standing by for your attack order on radio 0-0-2.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
Our recon shows that the infantry is on the high alert all over the region.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Neutralize Airbase"];
objective1 setSimpleTaskDescription ["Neutralize Airbase", "Neutralize Airbase", "Neutralize Airbase"];
